name: flutter_chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  # Dependency injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  # Functional programming
  dartz: ^0.10.1
  # Data classes
  freezed_annotation: ^2.4.1

  # Core packages
  base:
    path: ./packages/core/base
  chicken_storage:
    path: ./packages/core/chicken_storage
  chicken_http:
    path: ./packages/core/chicken_http
  token_service:
    path: ./packages/core/token_service

  # Feature packages
  user_onboarding:
    path: ./packages/feature/user_onboarding

  

  freezed: ^2.4.5
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  melos: ^3.1.1
  very_good_analysis: ^5.1.0
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
